### ISSUE TITLE
Tab is used instead of Spaces

### ISSUE THREAD

**Issue by Soldia1138** [BaerMitUmlaut/Poppy#24]
https://github.com/BaerMitUmlaut/Poppy/blob/28cef3cf2a1078f168c1edf90645ce27ab492fd7/functions/atomics/fn_replaceInsignia.sqf#L19

**Comment by BaerMitUmlaut** [comment]
😱

**Comment by Soldia1138** [comment]
Yes. It destroys every sqf-validator check and CI pipelines 😛 

Will open an extensive PR to fix it :wink:

**Comment by Soldia1138** [comment]
https://github.com/BaerMitUmlaut/Poppy/pull/20
